const routes = [
    {
      path:"/",
      redirect:"/login"//重定向到登录
    },
    {
      path:"/login",//登录
      name:"login",
      component:()=>import("@/views/login/login.vue")//promise函数
    },
    {
      path:"/register",//注册
      name:"register",
      component:()=>import("@/views/register/register.vue")
    },
    {
      path:"/home",//首页
      name:"home",
      component:()=>import("@/views/home/home.vue"),
      redirect:"/home/list",
      children:[
        {
          path:"list",//列表
          name:"list",
          meta:{
            show:true
          },
          component:()=>import("@/views/home/list/list.vue"),
          children:[
            {
              path:"file",//文档
              name:"file",
              meta:{
                show:true
              },
              component:()=>import("@/views/home/list/file/file.vue")
            },
            {
              path:"know",//知识库
              name:"know",
              meta:{
                show:true
              },
              component:()=>import("@/views/home/list/know/know.vue")
            }
          ]
        },
        {
          path:"detail",//详情页
          name:"detail",
          meta:{
            show:false
          },
          component:()=>import("@/views/home/detail/detail.vue")
        },
        {
          path:"search",//搜索页
          name:"search",
          meta:{
            show:false
          },
          component:()=>import("@/views/home/search/search.vue")
        },
        {
          path:"addfile",//新增文档页
          name:"addfile",
          meta:{
            show:false
          },
          component:()=>import("@/views/home/addfile/addfile.vue")
        },
        {
          path:"addknow",//新增知识库页
          name:"addknow",
          meta:{
            show:false
          },
          component:()=>import("@/views/home/addknow/addknow.vue")
        },
      ]
    }
  ]
  export default routes;